baseURL: "https://sanshay.github.io"
languageCode: "en-us"
title: "Sanshay Katyal"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Sanshay Katyal"
  namecolor: ffc107
  profession: "IoT Enthusiast"
  github: "https://github.com/sanshay"
  gitlab: "https://gitlab.com/sanshay"
  linkedin: "https://linkedin.com/sanshay-katyal"
  twitter: "https://twitter.com/sanshay_k"
  instagram: "https://instagram.com/dunkenmaster.1"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "I am a meticulous and systematized individual professed at IoT and various other platforms. I have a strong competence to handle complex projects with experience in FPV Drones and DevOps."
  descripe_l2_person: "You can find my works [here](#projects)"
  skills:
    - name: Python
      percentage: 90
    - name: Linux
      percentage: 75
    - name: Web Development
      percentage: 85
    - name: Internet of Things
      percentage: 95

  # Experience
  disable_experience: false
  experience:
    - company: "Triton Electric Vehicle"
      id: "triton-developer"   #// use this, when you want to change the id(used for navigation)
      role: "Embedded Software Engineer"
      startdate: June 2022
      enddate: present
      featuredpoints:
        # - point: Lead backend developer for a product.
        # - point: Created a frontend design for a product.
    - company: "HashOrg Tech"
      id: "hashorg-developer" #// use this, when you want to change the id(used for navigation)
      role: "Software Engineer"
      startdate: May 2022
      enddate: June 2022
      featuredpoints:
        # - point: Lead backend developer for a product.
        # - point: Created a frontend design for a product.
    - company: "MattsenKumar LLC"
      id: "mattsen-associate" // use this, when you want to change the id(used for navigation)
      role: "Senior Associate"
      startdate: Sept 2020
      enddate: April 2022
      # featuredpoints:
      #   - point: Lead backend developer for a product.
      #   - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "B.tech"
      branch: "Computer Science"
      university: "Sharda university"
      startedyear: "2019"
      graduation: "2023"
    - degree: "Class XII"
      branch: "Senior Secondary"
      university: "Bharti Public School"
      startedyear: "2018"
      graduation: "2019"
    - degree: "Class X"
      branch: "Secondary"
      university: "Bharti Public School"
      startedyear: "2016"
      graduation: "2017"

  # Projects
  disable_projects: true
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "sanshaykatyal@gmail.com"

  # Footer
  socialiconfooter: false
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
